# Generated by Django 3.1.4 on 2021-01-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0001_initial'),
        ('aplicatie3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Project-based', 'Project-based'), ('Volunteering', 'Volunteering')], max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('how_to_apply', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie2.companies')),
            ],
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
